def invoice_customer(name, phone, today_date_and_time, user_purchased_laptops, shipping_cost, grand_total):
    with open(str(name)+str(phone)+".txt","w")as file:
        file.write("\n")
        file.write("\t \t \t \t laptop shop bill ")
        file.write("\n")
        file.write("\t \t kamalpokhari, kathamandu | phone no: 9813180929 ")
        file.write("\n")
        file.write("----------------------------------------------------------------------------------------------------------\n")
        file.write("Laptop Details are: ")
        file.write("----------------------------------------------------------------------------------------------------------\n")
        file.write("Name of the custumer:"+ str(name))
        file.write("contact no:"+ str(phone))
        file.write("date and time of purchased: "+str(today_date_and_time))
        file.write("------------------------------------------------------------------------------------------------------------")
        file.write("\n")
        file.write("purchased details are:")
        file.write("------------------------------------------------------------------------------------------------------------")
        file.write("Item Name \t \t total quantity \t \t unit price \t \t total")
        file.write("-------------------------------------------------------------------------------------------------------------")
        for i in user_purchased_laptops:
            file.write(str(i[0])+"\t\t\t"+str(i[1])+"\t\t\t"+str(i[2])+"\t\t\t"+"$"+str(i[3]))
        file.write("----------------------------------------------------------------------------------------------------------")
        file.write("\n")
        if shipping_cost:
            file.write("your shipping cost is:"+""+str(shipping_cost)+"\n")
            file.write("\n")
            file.write("grand_total: $"+str(grand_total))
            file.write("\n")
            file.write("***note: shipping cost is added to the grand total***"+"\n")
        else:
            file.write("grand total: $"+str(grand_total))
            
def invoice_manufacturer(name,phone,today_date_and_time,user_purchased_laptops,VAT,grand_total):
    with open(str(name)+str(phone)+".txt","w")as file:
        file.write("\n")
        file.write("\t \t \t \t laptop shop bill ")
        file.write("\n")
        file.write("\t \t kamalpokhari, kathamandu | phone no: 9813180929 ")
        file.write("\n")
        file.write("----------------------------------------------------------------------------------------------------------\n")
        file.write("Laptop Details are: ")
        file.write("----------------------------------------------------------------------------------------------------------\n")
        file.write("Name of the custumer:"+ str(name))
        file.write("contact no:"+ str(phone))
        file.write("date and time of purchased: "+str(today_date_and_time))
        file.write("------------------------------------------------------------------------------------------------------------")
        file.write("\n")
        file.write("purchased details are:")
        file.write("------------------------------------------------------------------------------------------------------------")
        file.write("Item Name \t \t total quantity \t \t unit price \t \t total")
        file.write("-------------------------------------------------------------------------------------------------------------")
        for i in user_purchased_laptops:
            file.write(str(i[0])+"\t\t\t"+str(i[1])+"\t\t\t"+str(i[2])+"\t\t\t"+"$"+str(i[3]))
        file.write("----------------------------------------------------------------------------------------------------------")
        file.write("\n")
        file.write("your vat is:"+""+str(VAT)+"\n")
        file.write("\n")
        file.write("grand_total: $"+ str(grand_total+VAT))
        file.write("\n")
        file.write("***note: VAT is added to the grand total"+"\n")

